"""empty message

Revision ID: 88a84b40699c
Revises: 7f98f021608b
Create Date: 2019-07-19 13:31:00.986030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88a84b40699c'
down_revision = '7f98f021608b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_post_body', table_name='post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_post_body', 'post', ['body'], unique=False)
    # ### end Alembic commands ###
